language: bash
services: docker
before_script:
- export RELEASE_DATE=$(date +%Y.%m.%d)
script:
- docker build --no-cache --pull -t brinkos/iso-builder .
- docker images
- sudo losetup -f
- docker run -i -t --privileged -v `pwd`/iso:/iso --rm brinkos/iso-builder
- sudo chmod -R 777 ./iso
- mv ./iso/*.iso ./iso/brinkOS_$RELEASE_DATE.iso
- ls -lart ./iso/
deploy:
  provider: releases
  api_key:
    secure: zDP5WAkti7gtOUnsk1l11lqmmPnL/PQtgB9040ZysBV8Z88H229KygRK2qEaaqewYV14Q6T/Wbx4QtAkSpZFyOkN4EdyrE+OpvrrKxrEo+olbSIs2EHQtW2Zrjp7HvLPuqO9UhV6I+iFO9G7xyyqKrGRdAq/4cFhtzfg5uqj0k0lB/uDFEQc+taPRUQPpThoichffTwLQI3IbqPPDwfcBKbOIw2IrWNNilj5NCClIEeSBoaYSpv4t7g1GkjzudNe3XuCQ5BsDw8IcaJKzW2CmXtrhukWCHmq70nORBH6XsRF+oZwsth+NYb54fdorN8SI98RPK9dlbNp2aoxP2J79vXVaqm3RO2BOxsd7VpnTVTaX2GPLYSKfqiRTvlJbPo85wgMJUNq7NfdZ2X5hIC7LHqcULrvPTifP8kkZwEcPgJcMfJxtvV4foP4lkxDNUd54kGTsbWp0cVfZ91Itw3Urm4id6TG22nR1CvgML1N8auLW9/KiohtfNIFLNinNlRykxAqSiXQJBI7KVmkli0ItZkgU5yFw/XXuuUuljHG1YfGmj7Ia+1AaVWT7DuLVvaTQpr/GOjaDwSlc9iPJwJHbA2684PyTGi4R+CYQdUwLLHLsc7QG8ylLdtnVBKa0GjNe5kFy0oOMVKQCa8Bsd7MOzqirHzb4IcAg8RB8BUt8f0=
  file: ./iso/brinkOS_$RELEASE_DATE.iso
  skip_cleanup: true
  on:
    repo: brinkOS/brinkOS
    tags: true
